export const all_routes = {
  dashboard: "/",
  signin: "/signin",
  signinthree: "/signin-3",
  registerThree: "/register-3",
  studentSignup: "/student-signup",
  studentSubjects: "/student/subjects",
  studentUpload: "/student/upload",
  studentResults: "/student/results",
  studentResultDetail: "/student/results/:id",
  adminSubjects: "/admin/subjects",
  adminModelAnswers: "/admin/model-answers",
  adminSubmissions: "/admin/submissions",
  adminResults: "/admin/results",
  adminResultDetail: "/admin/results/:id",
  users: "/users",
};
